//ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//AUTH
export const SET_LOGGED = 'SET_LOGGED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
//LOADING
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';
//ORGANIZATION
export const GET_ALL_ORGS = 'GET_ALL_ORGS';
export const ADD_NEW_ORG = 'ADD_NEW_ORG';
export const SHOW_EDIT = 'SHOW_EDIT';
export const UPDATE_ORG = 'UPDATE_ORG';
export const DELETE_ORG = 'DELETE_ORG';

//PLACE
export const GET_ALL_PLACES = 'GET_ALL_PLACES';
export const ADD_NEW_PLACE = 'ADD_NEW_PLACE';
export const SHOW_EDIT_PLACE = 'SHOW_EDIT_PLACE';
export const UPDATE_PLACE = 'UPDATE_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

//GROUP
export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';
export const SHOW_EDIT_GROUP = 'SHOW_EDIT_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const SELECT_GROUP_iCON = 'SELECT_GROUP_iCON';
export const SHOW_GROUP_ICON = 'SHOW_GROUP_ICON';
//activity
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const ADD_NEW_ACTIVITY = 'ADD_NEW_ACTIVITY';
export const SHOW_EDIT_ACTIVITY = 'SHOW_EDIT_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ACTIVITY_BY_ID = 'ACTIVITY_BY_ID';

export const ACTIVITY_SELECT_ORG = 'ACTIVITY_SELECT_ORG';
export const ACTIVITY_DESELECT_ORG = 'ACTIVITY_DESELECT_ORG';
export const ADD_ORG_TO_ACTIVITY = 'ADD_ORG_TO_ACTIVITY';
export const DELETE_ORG_FROM_ACTIVITY = 'DELETE_ORG_FROM_ACTIVITY';

export const ACTIVITY_SELECT_GROUP = 'ACTIVITY_SELECT_GROUP';
export const ACTIVITY_DESELECT_GROUP = 'ACTIVITY_DESELECT_GROUP';
export const ADD_GROUP_TO_ACTIVITY = 'ADD_GROUP_TO_ACTIVITY';
export const DELETE_GROUP_FROM_ACTIVITY = 'DELETE_GROUP_FROM_ACTIVITY';
